### ISSUE TITLE
History is not entirely migrated on a fresh profile

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla-services/services-engineering#53]
**Prerequisites:** 
- use an user with decent amount of data 
- The user is disconnected during migration

**Steps to reproduce:**
1. Launch Firefox using a new fresh (clean) profile.
2. Login using the user mentioned in prerequisites.
3. Perform a Sync.
4. Check the history.

**Expected results:**
The Firefox account successfully pulls down all existing data on a fresh profile.

**Actual Results:**
History is not entirely migrated.

**Additional notes:**
- This issue was reproduce using the following user:
produser16@mailinator.com - 128812765 (old ID) - 144154479 (new ID)
- I am attaching the sync logs.
[sync-error1.txt](https://github.com/mozilla-services/services-engineering/files/4553205/sync-error1.txt)
[sync-error2.txt](https://github.com/mozilla-services/services-engineering/files/4553206/sync-error2.txt)

![Screenshot_3](https://user-images.githubusercontent.com/18114210/80625373-c9c1dc80-8a55-11ea-8f24-099012054961.png)

**Comment by jrconlin** [comment]
As I understand from talking with @erkolson, there was some confusion around the timing of when some accounts were moved from their original sync nodes to a specifically created "migration transition node". This lead to some data being written to an account that would not be replicated to the to new transition node, which may have included history records. 

As I understand, the migration script did not report any errors associated with this account, meaning that all data that was accessible at time of migration was moved over. 

In light of this confusion, I don't believe we have enough info to determine if this is a problem in the service or if it's a problem in the testing, and suggest we close this issue for now.

**Comment by tublitzed** [comment]
@jrconlin can we do a test ourselves with Erik to confirm that this is a non-issue before closing it out?

**Comment by erkolson** [comment]
I've migrated 2 new clients for @rbillings today:
```
rllings+0504syncN4@mozilla.com 5850355 ff811e4e2c5043b0bd16e4ef1169bedf@api-accounts.stage.mozaws.net 5850372
rbillings+0504N2@mozilla.com 5850358 84a3e6a202ea4b89bd41c9beb84e066d@api-accounts.stage.mozaws.net 5850371
```

**Comment by rbillings** [comment]
Confirmed that 2 accounts migrated both history and bookmarks correctly, along with the urls and ids being updated correctly.

**Comment by tublitzed** [comment]
Thanks Erik and Rebecca. I'm going to close this one out.
