### ISSUE TITLE
syncstorage-rs logging

### ISSUE THREAD

**Issue by erkolson** [mozilla-services/services-engineering#62]
Is there a logging level that includes the request url path?  This could help correlate application errors to specific user behavior.

**Comment by jrconlin** [comment]
[Looks like we are](https://github.com/mozilla-services/syncstorage-rs/blob/master/src/web/middleware/sentry.rs#L121), in the sentry "extras" set. I believe that these show up as [`uri.path` ](https://sentry.prod.mozaws.net/operations/syncstorage-prod/issues/9035922/?query=is%3Aunresolved#extra)

**Comment by tublitzed** [comment]
@erkolson does that give you what you're after here since it looks like we have them passing through to Sentry already, or are you looking for something else here?

**Comment by jrconlin** [comment]
fwiw: here's an example in sentry:
![image](https://user-images.githubusercontent.com/35755/88336953-b8057380-ccea-11ea-9800-e3a37b728aaa.png)

**Comment by erkolson** [comment]
This helps, thanks!
