### ISSUE TITLE
Investigate syncstorage-rs stage timeouts

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/services-engineering#64]
On stage we see intermittent upstream timeouts (nginx to syncstorage-rs), e.g.:

`
textPayload: "2020/07/27 14:20:33 [error] 9#9: *2372281 upstream timed out (110: Connection timed out) while reading response header from upstream, client: ..., server: , request: "GET /1.5/.../info/configuration HTTP/1.1", upstream: "http://127.0.0.1:8000/1.5/.../info/configuration", host: "stage.sync.nonprod.cloudops.mozgcp.net"
`

These sometimes happen even when there's no load testing, and even on the least resource intensive endpoints (e.g. /info/configuration which doesn't even check out a db connection).

**Comment by erkolson** [comment]
We were seeing a max of 60s timeouts during stage loadtests, which alligns with a few timeout defaults.  I changed one of them to a higher value:
```
proxy_read_timeout 625s
```
And a subsequent load test showed requests taking up to 300s:
https://earthangel-b40313e5.influxcloud.net/d/TebY7D1Zk/sync-rs-stage?viewPanel=34&orgId=1&from=1596725404492&to=1596729540325

**Comment by pjenvey** [comment]
Closing as dupe of #63
