### ISSUE TITLE
Create a new repo/skeleton for Project Cumulus service

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/services-engineering#78]
Probably going with rust to begin with here, and w/ actix-web (maybe warp).

**Comment by jrconlin** [comment]
Honestly thinking that we should build out a skeleton that has the cores, since this will probably not be the only service we spin up.

(Basically, super primitive that has `slog-mozilla`, `cadence` (maybe with tags?), `actix-web`, the various dockerflow endpoints pre-built, `config`, etc.)

**Comment by tublitzed** [comment]
@pjenvey in addition to the generic skeleton repo, can we fork it so that we're setup to start filing tickets/etc specific to the cumulous work?

**Comment by tublitzed** [comment]
closing - new repo lives here. https://github.com/mozilla-services/fx-tiles

**Comment by tublitzed** [comment]
Errr...actually looks like fork is [in review](https://github.com/mozilla-services/fx-tiles/pull/1). Will keep open until that merges.

**Comment by pjenvey** [comment]
New repo initialization was merged
